/**
 * 阿里云百炼 DashScope「图像擦除补全」image-erase-completion（异步任务）。
 * @see 项目根目录 22.md、阿里云文档
 */

const SYNTHESIS_URL = 'https://dashscope.aliyuncs.com/api/v1/services/aigc/image2image/image-synthesis';

export function getDashscopeApiKey() {
  return String(process.env.DASHSCOPE_API_KEY || '').trim();
}

function toDataUrl(buf, mime) {
  const m = mime || 'image/jpeg';
  return `data:${m};base64,${buf.toString('base64')}`;
}

/**
 * @param {{ imageBuffer: Buffer; imageMime: string; maskBuffer: Buffer; fastMode?: boolean; dilateFlag?: boolean; addWatermark?: boolean }} opts
 * @returns {Promise<string>} task_id
 */
export async function createImageEraseTask(opts) {
  const apiKey = getDashscopeApiKey();
  if (!apiKey) throw new Error('未配置 DASHSCOPE_API_KEY（北京地域 API Key）');

  const imageMime = String(opts.imageMime || 'image/jpeg').toLowerCase();
  const body = {
    model: 'image-erase-completion',
    input: {
      image_url: toDataUrl(opts.imageBuffer, imageMime),
      mask_url: toDataUrl(opts.maskBuffer, 'image/png'),
    },
    parameters: {
      fast_mode: opts.fastMode !== false,
      /** 涂抹手写 mask 用 false；算法分割 mask 可 true */
      dilate_flag: opts.dilateFlag === true,
      /** 文档默认 true；此处默认关闭「Generated by AI」水印 */
      add_watermark: opts.addWatermark === true,
    },
  };

  const res = await fetch(SYNTHESIS_URL, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      'X-DashScope-Async': 'enable',
      'X-DashScope-DataInspection': 'enable',
    },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(180_000),
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    const msg = json.message || json.code || `HTTP ${res.status}`;
    throw new Error(typeof msg === 'string' ? msg : JSON.stringify(json));
  }
  const taskId = json.output?.task_id;
  if (!taskId) throw new Error('未取得任务 ID');
  return String(taskId);
}

/**
 * @param {string} taskId
 * @param {{ timeoutMs?: number }} [options]
 * @returns {Promise<string>} output_image_url
 */
export async function pollImageEraseTask(taskId, options = {}) {
  const apiKey = getDashscopeApiKey();
  if (!apiKey) throw new Error('未配置 DASHSCOPE_API_KEY');

  const timeoutMs = Number(options.timeoutMs) > 0 ? Number(options.timeoutMs) : 180_000;
  const deadline = Date.now() + timeoutMs;
  const url = `https://dashscope.aliyuncs.com/api/v1/tasks/${encodeURIComponent(taskId)}`;

  while (Date.now() < deadline) {
    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${apiKey}` },
      signal: AbortSignal.timeout(60_000),
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) {
      const msg = json.message || json.code || `HTTP ${res.status}`;
      throw new Error(typeof msg === 'string' ? msg : JSON.stringify(json));
    }
    const status = json.output?.task_status;
    if (status === 'SUCCEEDED') {
      const outUrl = json.output?.output_image_url;
      if (!outUrl) throw new Error('任务成功但无 output_image_url');
      return String(outUrl);
    }
    if (status === 'FAILED') {
      const m = json.output?.message || json.output?.code || '图像擦除失败';
      throw new Error(typeof m === 'string' ? m : JSON.stringify(json.output));
    }
    await new Promise((r) => setTimeout(r, 2000));
  }
  throw new Error('图像擦除任务超时');
}

export async function downloadHttpBuffer(imageUrl) {
  const res = await fetch(imageUrl, { redirect: 'follow', signal: AbortSignal.timeout(120_000) });
  if (!res.ok) throw new Error(`下载结果图失败: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const contentType = String(res.headers.get('content-type') || '').split(';')[0].trim();
  return { buf, contentType };
}
